### ISSUE TITLE
著名的img标签3像素问题

### ISSUE THREAD

**Issue by namedrj** [namedrj/cssSolution#1]
img标签在HTML5和HTML4.0.1的严格模式渲染的时候，下面会有几像素的空白。
解决办法：
1.img标签增加vertical-align:top|center|bottom (因为默认是baseline，所以解决办法就是，只要不是baseline就行)
```css
img {
    vertical-align: top;
}
```
2.img标签的父标签增加font-size:0;
3.img标签增加display:block;
