### ISSUE TITLE
导航栏快速布局

### ISSUE THREAD

**Issue by namedrj** [namedrj/cssSolution#2]
```css
/* 笔记：导航栏的快速布局 */
.nav-tabs li {
  float: left;
  display: flex;
  /*水平居中*/
  justify-content: center;
  /*垂直居中*/
  align-items: center;
  width: 100px;
  height: 75px;
}
```
